version: '3.8'

services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6380:6379"
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    container_name: rediscommander
    environment:
      - REDIS_HOSTS=local:redis:6379